=== Ensembl/ensembl-biomart/martj/src/java/org/biomart/builder/resources/MartBuilder-0.7.dtd
<!--
#
#        Copyright (C) 2006 EBI
# 
#        This library is free software; you can redistribute it and/or
#        modify it under the terms of the GNU Lesser General Public
#        License as published by the Free Software Foundation; either
#        version 2.1 of the License, or (at your option) any later version.
# 
#        This library is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the itmplied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#        Lesser General Public License for more details.
# 
#        You should have received a copy of the GNU Lesser General Public
#        Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

# DTD for MartBuilder XML files
# author: Richard Holland, <holland@ebi.ac.uk>
# version $Revision: 1.38 $, $Date: 2008-03-12 14:22:38 $, modified by $Author: rh4 $
# since: 0.1
-->

<!ELEMENT mart (jdbcSchema+,relation*,dataset*)>
<!ATTLIST mart outputDatabase CDATA #IMPLIED>
<!ATTLIST mart outputSchema CDATA #IMPLIED>
<!ATTLIST mart outputHost CDATA #IMPLIED>
<!ATTLIST mart outputPort CDATA #IMPLIED>
<!ATTLIST mart overrideHost CDATA #IMPLIED>
<!ATTLIST mart overridePort CDATA #IMPLIED>
<!ATTLIST mart nameCase CDATA #IMPLIED>
<!ATTLIST mart hideMaskedDataSets (true|false) #IMPLIED>
<!ATTLIST mart hideMaskedSchemas (true|false) #IMPLIED>

<!ELEMENT jdbcSchema (table+,relation*)>
<!ATTLIST jdbcSchema uniqueId CDATA #IMPLIED>
<!ATTLIST jdbcSchema driverClassName CDATA #REQUIRED>
<!ATTLIST jdbcSchema url CDATA #REQUIRED>
<!ATTLIST jdbcSchema databaseName CDATA #REQUIRED>
<!ATTLIST jdbcSchema schemaName CDATA #REQUIRED>
<!ATTLIST jdbcSchema username CDATA #REQUIRED>
<!ATTLIST jdbcSchema password CDATA #IMPLIED>
<!ATTLIST jdbcSchema name CDATA #REQUIRED>
<!ATTLIST jdbcSchema keyguessing (true|false) #REQUIRED>
<!ATTLIST jdbcSchema partitionRegex CDATA #IMPLIED>
<!ATTLIST jdbcSchema partitionExpression CDATA #IMPLIED>
<!ATTLIST jdbcSchema masked (true|false) #IMPLIED>
<!ATTLIST jdbcSchema hideMasked (true|false) #IMPLIED>

<!ELEMENT relation EMPTY>
<!ATTLIST relation id ID #REQUIRED>
<!ATTLIST relation cardinality (1|M) #REQUIRED>
<!ATTLIST relation originalCardinality (1|M) #REQUIRED>
<!ATTLIST relation firstKeyId IDREF #REQUIRED>
<!ATTLIST relation secondKeyId IDREF #REQUIRED>
<!ATTLIST relation status (MODIFIED|HANDMADE|INFERRED|INFERRED_INCORRECT) #REQUIRED>
<!ATTLIST relation visibleModified (true|false) #IMPLIED>

<!ELEMENT table (column+,primaryKey?,foreignKey*)>
<!ATTLIST table uniqueId CDATA #IMPLIED>
<!ATTLIST table id ID #REQUIRED>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST table ignore (true|false) #IMPLIED>
<!ATTLIST table inSchemaPartition CDATA #IMPLIED>

<!ELEMENT column EMPTY>
<!ATTLIST column id ID #REQUIRED>
<!ATTLIST column name CDATA #REQUIRED>
<!ATTLIST column visibleModified (true|false) #IMPLIED>
<!ATTLIST column inSchemaPartition CDATA #IMPLIED>

<!ELEMENT primaryKey EMPTY>
<!ATTLIST primaryKey id ID #REQUIRED>
<!ATTLIST primaryKey columnIds IDREFS #REQUIRED>
<!ATTLIST primaryKey status (HANDMADE|INFERRED|INFERRED_INCORRECT) #REQUIRED>
<!ATTLIST primaryKey visibleModified (true|false) #IMPLIED>

<!ELEMENT foreignKey EMPTY>
<!ATTLIST foreignKey id ID #REQUIRED>
<!ATTLIST foreignKey columnIds IDREFS #REQUIRED>
<!ATTLIST foreignKey status (HANDMADE|INFERRED|INFERRED_INCORRECT) #REQUIRED>
<!ATTLIST foreignKey visibleModified (true|false) #IMPLIED>

<!ELEMENT dataset (
compoundRelation*,subclassRelation*,maskedColumn*,
indexedColumn*,maskedRelation*,alternativeJoin*,transformStart*,maskedTable*,
mergedRelation*,loopbackRelation*,forcedRelation*,restrictedTable*,
restrictedRelation*,expressionColumn*,renamedTable*,
renamedColumn*,distinctRows*,noFinalLeftJoin*,skipOptimiser*,skipIndexOptimiser*,unrolledRelation*,explainHideMasked*,
visibleModified*,bigTable*,splitOptimiser*,tableHideMasked*)>
<!ATTLIST dataset name CDATA #REQUIRED>
<!ATTLIST dataset centralTableId IDREF #REQUIRED>
<!ATTLIST dataset optimiser (COLUMN_INHERIT|COLUMN_BOOL_INHERIT|COLUMN_BOOL_NULL_INHERIT|TABLE_INHERIT|TABLE_BOOL_INHERIT|TABLE_BOOL_NULL_INHERIT|NONE) #REQUIRED>
<!ATTLIST dataset indexOptimiser (true|false) #REQUIRED>
<!ATTLIST dataset invisible (true|false) #REQUIRED>
<!ATTLIST dataset masked (true|false) #IMPLIED>
<!ATTLIST dataset hideMasked (true|false) #IMPLIED>

<!ELEMENT explainHideMasked EMPTY>
<!ATTLIST explainHideMasked tableKey CDATA #REQUIRED>

<!ELEMENT tableHideMasked EMPTY>
<!ATTLIST tableHideMasked tableKey CDATA #REQUIRED>

<!ELEMENT visibleModified EMPTY>
<!ATTLIST visibleModified key CDATA #REQUIRED>

<!ELEMENT subclassRelation EMPTY>
<!ATTLIST subclassRelation relationId IDREF #REQUIRED>

<!ELEMENT compoundRelation EMPTY>
<!ATTLIST compoundRelation tableKey CDATA #REQUIRED>
<!ATTLIST compoundRelation relationId IDREF #REQUIRED>
<!ATTLIST compoundRelation n CDATA #REQUIRED>
<!ATTLIST compoundRelation parallel (true|false) #REQUIRED>

<!ELEMENT unrolledRelation EMPTY>
<!ATTLIST unrolledRelation relationId IDREF #REQUIRED>
<!ATTLIST unrolledRelation columnId IDREF #REQUIRED>
<!ATTLIST unrolledRelation reversed (true|false) #IMPLIED>

<!ELEMENT renamedTable EMPTY>
<!ATTLIST renamedTable tableKey CDATA #REQUIRED>
<!ATTLIST renamedTable newName CDATA #REQUIRED>

<!ELEMENT splitOptimiser EMPTY>
<!ATTLIST splitOptimiser tableKey CDATA #REQUIRED>
<!ATTLIST splitOptimiser colKey CDATA #REQUIRED>
<!ATTLIST splitOptimiser contentCol CDATA #REQUIRED>
<!ATTLIST splitOptimiser separator CDATA #REQUIRED>
<!ATTLIST splitOptimiser prefix (true|false) #IMPLIED>
<!ATTLIST splitOptimiser suffix (true|false) #IMPLIED>
<!ATTLIST splitOptimiser size CDATA #IMPLIED>

<!ELEMENT renamedColumn EMPTY>
<!ATTLIST renamedColumn tableKey CDATA #REQUIRED>
<!ATTLIST renamedColumn colKey CDATA #REQUIRED>
<!ATTLIST renamedColumn newName CDATA #REQUIRED>

<!ELEMENT maskedColumn EMPTY>
<!ATTLIST maskedColumn tableKey CDATA #REQUIRED>
<!ATTLIST maskedColumn colKey CDATA #REQUIRED>

<!ELEMENT indexedColumn EMPTY>
<!ATTLIST indexedColumn tableKey CDATA #REQUIRED>
<!ATTLIST indexedColumn colKey CDATA #REQUIRED>

<!ELEMENT maskedRelation EMPTY>
<!ATTLIST maskedRelation tableKey CDATA #REQUIRED>
<!ATTLIST maskedRelation relationId IDREF #REQUIRED>

<!ELEMENT alternativeJoin EMPTY>
<!ATTLIST alternativeJoin tableKey CDATA #REQUIRED>
<!ATTLIST alternativeJoin relationId IDREF #REQUIRED>

<!ELEMENT transformStart EMPTY>
<!ATTLIST transformStart tableKey CDATA #REQUIRED>
<!ATTLIST transformStart tableId IDREF #REQUIRED>

<!ELEMENT maskedTable EMPTY>
<!ATTLIST maskedTable tableKey CDATA #REQUIRED>

<!ELEMENT mergedRelation EMPTY>
<!ATTLIST mergedRelation relationId IDREF #REQUIRED>

<!ELEMENT loopbackRelation EMPTY>
<!ATTLIST loopbackRelation tableKey CDATA #REQUIRED>
<!ATTLIST loopbackRelation relationId IDREF #REQUIRED>
<!ATTLIST loopbackRelation diffColumnId IDREF #REQUIRED>

<!ELEMENT forcedRelation EMPTY>
<!ATTLIST forcedRelation tableKey CDATA #REQUIRED>
<!ATTLIST forcedRelation relationId IDREF #REQUIRED>

<!ELEMENT distinctRows EMPTY>
<!ATTLIST distinctRows tableKey CDATA #REQUIRED>

<!ELEMENT noFinalLeftJoin EMPTY>
<!ATTLIST noFinalLeftJoin tableKey CDATA #REQUIRED>

<!ELEMENT skipOptimiser EMPTY>
<!ATTLIST skipOptimiser tableKey CDATA #REQUIRED>

<!ELEMENT skipIndexOptimiser EMPTY>
<!ATTLIST skipIndexOptimiser tableKey CDATA #REQUIRED>

<!ELEMENT restrictedTable EMPTY>
<!ATTLIST restrictedTable tableKey CDATA #REQUIRED>
<!ATTLIST restrictedTable tableId IDREF #REQUIRED>
<!ATTLIST restrictedTable aliasColumnIds IDREFS #REQUIRED>
<!ATTLIST restrictedTable aliasNames CDATA #REQUIRED>
<!ATTLIST restrictedTable expression CDATA #REQUIRED>

<!ELEMENT bigTable EMPTY>
<!ATTLIST bigTable tableKey CDATA #REQUIRED>
<!ATTLIST bigTable tableId IDREF #REQUIRED>
<!ATTLIST bigTable bigness CDATA #REQUIRED>

<!ELEMENT restrictedRelation EMPTY>
<!ATTLIST restrictedRelation tableKey CDATA #REQUIRED>
<!ATTLIST restrictedRelation relationId IDREF #REQUIRED>
<!ATTLIST restrictedRelation index CDATA #REQUIRED>
<!ATTLIST restrictedRelation leftAliasColumnIds IDREFS #REQUIRED>
<!ATTLIST restrictedRelation leftAliasNames CDATA #REQUIRED>
<!ATTLIST restrictedRelation rightAliasColumnIds IDREFS #REQUIRED>
<!ATTLIST restrictedRelation rightAliasNames CDATA #REQUIRED>
<!ATTLIST restrictedRelation expression CDATA #REQUIRED>

<!ELEMENT expressionColumn EMPTY>
<!ATTLIST expressionColumn tableKey CDATA #REQUIRED>
<!ATTLIST expressionColumn colKey CDATA #REQUIRED>
<!ATTLIST expressionColumn aliasColumnNames CDATA #REQUIRED>
<!ATTLIST expressionColumn aliasNames CDATA #REQUIRED>
<!ATTLIST expressionColumn expression CDATA #REQUIRED>
<!ATTLIST expressionColumn groupBy  (true|false) #REQUIRED>

<!ELEMENT datasetPartitionTable (partitionRegex*,partitionApplication*)>
<!ATTLIST datasetPartitionTable name CDATA #REQUIRED>
<!ATTLIST datasetPartitionTable selectedColumns CDATA #REQUIRED>

<!ELEMENT partitionRegex EMPTY>
<!ATTLIST partitionRegex name CDATA #REQUIRED>
<!ATTLIST partitionRegex match CDATA #REQUIRED>
<!ATTLIST partitionRegex replace CDATA #REQUIRED>

<!ELEMENT partitionApplication EMPTY>
<!ATTLIST partitionApplication name CDATA #REQUIRED>
<!ATTLIST partitionApplication dimension CDATA #IMPLIED>
<!ATTLIST partitionApplication pCols CDATA #REQUIRED>
<!ATTLIST partitionApplication dsCols CDATA #REQUIRED>
<!ATTLIST partitionApplication relationIds IDREFS #REQUIRED>
<!ATTLIST partitionApplication nameCols CDATA #REQUIRED>
<!ATTLIST partitionApplication compounds CDATA #REQUIRED>

=== Ensembl/ensembl-biomart/martbuilder_xml/v88_xml/vega_88.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mart PUBLIC "-//EBI//DTD MartBuilder 0.7-//EBI//DTD MartBuilder " "http://www.biomart.org/DTD/MartBuilder-0.7.dtd">
<mart outputDatabase="vega_mart_85" outputSchema="vega_mart_85" outputHost="localhost" outputPort="18002" overrideHost="ens-staging2" overridePort="3306" nameCase="0" hideMaskedDataSets="true" hideMaskedSchemas="false">
	<jdbcSchema uniqueId="1" driverClassName="com.mysql.jdbc.Driver" url="jdbc:mysql://localhost:24519/master_schema_88" databaseName="master_schema_88" schemaName="master_schema_88" username="ensadmin" password="ensembl" name="vega_gene" keyguessing="true" masked="false" hideMasked="true" partitionRegex="^(.)[^_]+_([^_]+)_vega_88_[0-9]*$" partitionExpression="$1$2">
		<table uniqueId="81" id="1" name="seq_region_synonym" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="2" name="seq_region_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="3" name="synonym" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="4" name="seq_region_synonym_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="5" name="external_db_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="6" columnIds="4" status="INFERRED" visibleModified="false"/>
			<foreignKey id="7" columnIds="5" status="INFERRED" visibleModified="false"/>
			<foreignKey id="8" columnIds="2" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="38" id="9" name="misc_feature_misc_set" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="10" name="misc_feature_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="11" name="misc_set_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="12" columnIds="10,11" status="INFERRED" visibleModified="false"/>
			<foreignKey id="13" columnIds="11" status="INFERRED" visibleModified="false"/>
			<foreignKey id="14" columnIds="10" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="33" id="15" name="marker_synonym" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="16" name="marker_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="17" name="name" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="18" name="source" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="19" name="marker_synonym_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="20" columnIds="19" status="INFERRED" visibleModified="false"/>
			<foreignKey id="21" columnIds="16" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="60" id="22" name="seq_region_attrib" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="23" name="seq_region_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="24" name="attrib_type_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="25" name="value" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<foreignKey id="26" columnIds="24" status="INFERRED" visibleModified="false"/>
			<foreignKey id="27" columnIds="23" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="92" id="28" name="transcript_intron_supporting_evidence" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="29" name="transcript_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="30" name="intron_supporting_evidence_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="31" name="next_exon_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="32" name="previous_exon_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="33" columnIds="30,29" status="INFERRED" visibleModified="false"/>
			<foreignKey id="34" columnIds="29" status="INFERRED" visibleModified="false"/>
			<foreignKey id="35" columnIds="30" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="13" id="36" name="dna_align_feature" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="37" name="cigar_line" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="38" name="external_data" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="39" name="hcoverage" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="40" name="hit_strand" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="41" name="evalue" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="42" name="seq_region_end" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="43" name="hit_end" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="44" name="analysis_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="45" name="score" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="46" name="seq_region_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="47" name="perc_ident" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="48" name="hit_start" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="49" name="external_db_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="50" name="seq_region_strand" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="51" name="dna_align_feature_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="52" name="seq_region_start" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="53" name="hit_name" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="54" columnIds="51" status="INFERRED" visibleModified="false"/>
			<foreignKey id="55" columnIds="44" status="INFERRED" visibleModified="false"/>
			<foreignKey id="56" columnIds="49" status="INFERRED" visibleModified="false"/>
			<foreignKey id="57" columnIds="46" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="72" id="58" name="unmapped_object" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="59" name="query_score" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="60" name="parent" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="61" name="identifier" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="62" name="external_db_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="63" name="target_score" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="64" name="unmapped_reason_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="65" name="ensembl_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="66" name="type" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="67" name="ensembl_object_type" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="68" name="analysis_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="69" name="unmapped_object_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<primaryKey id="70" columnIds="69" status="INFERRED" visibleModified="false"/>
			<foreignKey id="71" columnIds="68" status="INFERRED" visibleModified="false"/>
			<foreignKey id="72" columnIds="64" status="INFERRED" visibleModified="false"/>
			<foreignKey id="73" columnIds="62" status="INFERRED" visibleModified="false"/>
		</table>
		<table uniqueId="44" id="74" name="peptide_archive" ignore="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus">
			<column id="75" name="peptide_archive_id" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="76" name="md5_checksum" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
			<column id="77" name="peptide_seq" visibleModified="false" inSchemaPartition="hsapiens,mmusculus,sscrofa,drerio,rnorvegicus"/>
