=== Ensembl/ensembl-biomart/data/XML/DatasetConfig.dtd
<!ENTITY % desc_data 
                  "internalName CDATA #REQUIRED  
                   displayName CDATA #IMPLIED    
                   description CDATA #IMPLIED
                   hidden      CDATA #IMPLIED">

                   
<!ELEMENT DatasetConfig (Option*, MainTable+, Key*, Importable*, Exportable*, FilterPage+, AttributePage+)>
<!ATTLIST DatasetConfig %desc_data;
                      dataset             CDATA #REQUIRED
                      type                CDATA #IMPLIED
                      visible             CDATA #IMPLIED
                      optional_parameters CDATA #IMPLIED>

<!ELEMENT MainTable (#PCDATA)>

<!ELEMENT Key (#PCDATA)>

<!ELEMENT FilterPage (FilterGroup+)>
<!ATTLIST FilterPage %desc_data;>

<!ELEMENT FilterGroup (FilterCollection+)>
<!ATTLIST FilterGroup %desc_data;>

<!ELEMENT FilterCollection (FilterDescription+)>
<!ATTLIST FilterCollection
                   %desc_data;>
                    
<!ELEMENT FilterDescription (Option*)>
<!ATTLIST FilterDescription
                   %desc_data;
                   type          (boolean | boolean_list | boolean_num
		   | drop_down_basic_filter | list | id_list | text | text_entry_basic_filter | tree) "list"
                   field          CDATA #IMPLIED
                   qualifier      CDATA #IMPLIED
                   legal_qualifiers          CDATA #IMPLIED
                   tableConstraint    CDATA #IMPLIED
                   key                CDATA #IMPLIED
                   value              CDATA #IMPLIED>
                   
<!ELEMENT AttributePage (AttributeGroup+)>
<!ATTLIST AttributePage %desc_data;>

<!ELEMENT AttributeGroup (AttributeCollection+)>
<!ATTLIST AttributeGroup %desc_data;>

<!ELEMENT AttributeCollection (AttributeDescription+)>
<!ATTLIST AttributeCollection
                  %desc_data;
                   maxSelect    CDATA #IMPLIED>

<!ELEMENT AttributeDescription EMPTY>
<!ATTLIST AttributeDescription
                    %desc_data;
                    field          CDATA #REQUIRED
                    tableConstraint  CDATA #REQUIRED
                    key              CDATA #REQUIRED
                    maxLength         NMTOKEN #IMPLIED
                    source                CDATA #IMPLIED
                    homepageURL  CDATA #IMPLIED
                    linkoutURL          CDATA #IMPLIED>

<!ELEMENT Option (Option|PushAction|PushAction|Option)*>
<!ATTLIST Option 
                 %desc_data;
                 isSelectable  CDATA #REQUIRED
                 value         CDATA #IMPLIED
                 type          (boolean | boolean_list | boolean_num | drop_down_basic_filter | list | text | text_entry_basic_filter | tree) "list"
                 field     CDATA #IMPLIED
                 qualifier CDATA #IMPLIED
                 legal_qualifiers     CDATA #IMPLIED
                 tableConstraint    CDATA #IMPLIED
                 key                CDATA #IMPLIED>

<!ELEMENT PushAction (Option)+>
<!ATTLIST PushAction
				%desc_data;
				ref CDATA #REQUIRED>

=== Ensembl/ensembl-biomart/martj/data/unitTests/testDatasetConfigRegFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DatasetConfig SYSTEM "classpath:data/XML/DatasetConfig.dtd">
<DatasetConfig dataset="test" description="For Testing Purposes Only" displayName="Test of a File Registry DatasetConfig" internalName="test_datasetview_registry_file">
  <Option description="For Testing Purposes Only" displayName="A Test DatasetConfig Option" internalName="dataset option" isSelectable="true"/>
  <DefaultFilter value="1">
    <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="test_id" internalName="testDefaultFilterDescription" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
  </DefaultFilter>
  <MainTable> test_MainTable</MainTable>
  <Key>test_Key</Key>
  <FilterPage description="For Testing Purposes Only" displayName="Test A Filter Page" internalName="testFilterPage">
    <DSFilterGroup description="For Testing Purposes Only" displayName="Test A DSFilterGroup:" handler="testHandler" internalName="testDSFilterGroup"/>
    <FilterGroup description="For Testing Purposes Only" displayName="Test A FilterGroup:" internalName="testFilterGroup">
      <FilterCollection description="For Testing Purposes Only" displayName="Test of a FilterCollection" internalName="testFilterCollection">
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="test_id" internalName="testFilterDescription" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
        <FilterDescription description="For Testing Purposes Only" displayName="Filter With Enable" field="enable_test_id" internalName="enableFilter" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Enable ref="testFilterDescription" valueCondition="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="Filter With Disable" field="disable_test_id" internalName="disableFilter" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Disable ref="testFilterDescription" valueCondition="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="handlerField" handler="testHandler" internalName="testHandlerFilterDescription" legal_qualifiers="in,=" qualifier="in" type="list"/>
      </FilterCollection>
      <FilterCollection description="For Testing Purposes Only" displayName="A TEST OF Options" internalName="testOptionsCollection">
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Value Option" field="value_option_id" internalName="filterDescriptionValueOption" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
          <Option internalName="valueOption" isSelectable="true" value="1"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Tree Value Option" field="test_id" internalName="filterDescriptionTreeValueOption" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="tree_value_dm" type="list">
          <Option internalName="treeValueOption" isSelectable="false" value="">
            <Option internalName="valueOption" isSelectable="true" value="1"/>
          </Option>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST Option Filters" internalName="FilterDescriptionOptionFilters" type="list">
          <Option description="For Testing Purposes Only" displayName="A Test Option Filter" field="test_id" internalName="filterOptionOne" isSelectable="true" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="filterOne_dm" type="list"/>
          <Option description="For Testing Purposes Only" displayName="A Test Option Filter" field="test_id" internalName="filterOptionTwo" isSelectable="true" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="filterTwo_dm" type="list"/>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST OF OPTION WITH PUSHACTION" internalName="FilterDescriptionOptionPushAction" type="list">
          <Option description="For Testing Purposes Only" displayName="A TEST OPTION WITH PUSHACTION" field="pushActionOption_id" internalName="pushActionOption" isSelectable="true" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list">
            <PushAction description="For Testing Purposes Only" displayName="A TEST PUSHACTION" internalName="TestValuePushAction" ref="testFilterDescription">
              <Option description="For Testing Purposes Only" displayName="A TEST PUSHACTION OPTION" internalName="testPushActionOption" isSelectable="true" value="1"/>
            </PushAction>
          </Option>
        </FilterDescription>
        <FilterDescription description="For Testing Purposes Only" displayName="A TEST OF A PUSHACTION FILTER OPTION" internalName="testPushActionOptionFilter" type="list">
          <Option description="For Testing Purposes Only" displayName="A TEST OPTION WITH PUSHACTION FILTER OPTION" internalName="PushActionFilterOption" isSelectable="true">
            <PushAction description="For Testing Purposes Only" displayName="A TEST PUSHACTION WITH OPTION FILTER" internalName="OptionFilterPushAction" ref="testFilterDescription">
              <Option description="For Testing Purposes Only" displayName="A TEST FILTER OPTION IN A PUSHACTION" field="pushActionFilterOption_id" internalName="PushActionFilterOption" isSelectable="true" key="gene_id_key" legal_qualifiers="in,=" qualifier="in" tableConstraint="gene_main" type="list"/>
            </PushAction>
          </Option>
        </FilterDescription>
      </FilterCollection>
    </FilterGroup>
  </FilterPage>
  <AttributePage description="For Testing Purposes Only" displayName="Test of an Attribute Page" internalName="testAttributePage">
    <DSAttributeGroup description="For Testing Purposes Only" displayName="test of an DSAttribute Group:" handler="testHandler" internalName="testDSAttributeGroup"/>
    <AttributeGroup description="For Testing Purposes Only" displayName="test of an Attribute Group:" internalName="testAttributeGroup">
      <AttributeCollection description="For Testing Purposes Only" displayName="Test of an AttributeCollection:" internalName="testAttributeCollection" maxSelect="1">
        <AttributeDescription description="For Testing Purposes Only" displayName="Test of a AttributeDescription" field="test_id" homepageURL="http://test.org" internalName="testAttributeDescription" key="gene_id_key" linkoutURL="http://test.org?test" maxLength="1" source="test source" tableConstraint="gene_main"/>
      </AttributeCollection>
    </AttributeGroup>
  </AttributePage>
</DatasetConfig>
