=== Ensembl/ensembl-biomart/martj/data/xmltest/test.dtd
<!ENTITY % desc_data 
                  "internalName CDATA #REQUIRED  
                   displayName CDATA #IMPLIED    
                   description CDATA #IMPLIED"
>

<!-- Ensembl Source, Homepage, and LinkoutURL for AttributeDescriptions -->

<!-- Top-level Objects --> 
<!ELEMENT MartConfiguration (FilterDescription, Dataset+)>
<!ATTLIST MartConfiguration %desc_data;>
                   
<!ELEMENT Dataset (Option*, DefaultFilter*, StarBase+, PrimaryKey+, FilterPage+, AttributePage+)>
<!ATTLIST Dataset %desc_data;>

<!ELEMENT StarBase (#PCDATA)>

<!ELEMENT PrimaryKey (#PCDATA)>

<!ELEMENT FilterPage (FilterGroup|DSFilterGroup|DSFilterGroup|FilterGroup)+>
<!ATTLIST FilterPage %desc_data;>

<!ELEMENT FilterGroup (FilterCollection+)>
<!ATTLIST FilterGroup %desc_data;>

<!ELEMENT DSFilterGroup EMPTY>
<!ATTLIST DSFilterGroup %desc_data;
                        handler  CDATA #IMPLIED>

<!ELEMENT FilterCollection (FilterDescription+)>
<!ATTLIST FilterCollection
                   %desc_data;>
                    
<!ELEMENT FilterDescription (Option|Enable|Disable|Enable|Option|Disable)*>
<!ATTLIST FilterDescription
                   %desc_data;
                   type               CDATA #REQUIRED
                   field          CDATA #IMPLIED
                   qualifiers          CDATA #IMPLIED
                   tableConstraint    CDATA #IMPLIED
                   handler            CDATA #IMPLIED>

<!ELEMENT Enable EMPTY>
<!ATTLIST Enable ref CDATA #REQUIRED
                 valueCondition CDATA #IMPLIED>

<!ELEMENT Disable EMPTY>
<!ATTLIST Disable ref CDATA #REQUIRED
                  valueCondition CDATA #IMPLIED>
                   
<!ELEMENT AttributePage (AttributeGroup|DSAttributeGroup|DSAttributeGroup|AttributeGroup)+>
<!ATTLIST AttributePage %desc_data;>

<!ELEMENT AttributeGroup (AttributeCollection+)>
<!ATTLIST AttributeGroup %desc_data;>

<!ELEMENT DSAttributeGroup EMPTY>
<!ATTLIST DSAttributeGroup %desc_data;
                           handler CDATA #IMPLIED>

<!ELEMENT AttributeCollection (AttributeDescription+)>
<!ATTLIST AttributeCollection
                  %desc_data;
                   maxSelect    CDATA #IMPLIED>

<!ELEMENT AttributeDescription EMPTY>
<!ATTLIST AttributeDescription
                    %desc_data;
                    field          CDATA #REQUIRED
                    tableConstraint  CDATA #IMPLIED
                    maxLength         NMTOKEN #IMPLIED
                    source                CDATA #IMPLIED
                    homepageURL  CDATA #IMPLIED
                    linkoutURL          CDATA #IMPLIED>

<!ELEMENT Option (Option|PushOptions|PushOptions|Option)*>
<!ATTLIST Option 
                 %desc_data;
                 isSelectable  CDATA #REQUIRED
                 value         CDATA #IMPLIED
		         ref           CDATA #IMPLIED
                 type          CDATA #IMPLIED
                 field     CDATA #IMPLIED
                 qualifiers     CDATA #IMPLIED
                 tableConstraint    CDATA #IMPLIED
                 handler        CDATA #IMPLIED>

<!ELEMENT PushOptions (Option)+>
<!ATTLIST PushOptions
				%desc_data;
				ref CDATA #REQUIRED>

<!ELEMENT DefaultFilter (FilterDescription)>
<!ATTLIST DefaultFilter value CDATA #REQUIRED>

=== Ensembl/ensembl-biomart/data/xmltest/test_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MartConfiguration SYSTEM "test.dtd">
<MartConfiguration internalName="test_file">
  <FilterDescription internalName="testLayout" type="text-entry"/>
  <Dataset internalName="test_dataset">
    <StarBase>test_starbase</StarBase>
    <PrimaryKey>test_primaryKey</PrimaryKey>
    <FilterPage internalName="testFilterPage">
      <FilterGroup internalName="testFilterGroup">
        <FilterCollection internalName="testFilterCollection">
          <FilterDescription description="For Testing Purposes Only" displayName="A TEST ID, DOESNT EXIST" field="test_id" internalName="testFilterDescription" qualifiers="in,=" tableConstraint="gene_main" type="list"></FilterDescription>
        </FilterCollection>
      </FilterGroup>
    </FilterPage>
    <AttributePage internalName="testAttributePage">
      <AttributeGroup internalName="testAttributeGroup">
        <AttributeCollection internalName="testAttributeCollection" maxSelect="1">
          <AttributeDescription description="For Testing Purposes Only" displayName="Test of a AttributeDescription" field="test_id" homepageURL="http://test.org" internalName="testAttributeDescription" linkoutURL="http://test.org?test" maxLength="1" source="test source" tableConstraint="gene_main"></AttributeDescription>
        </AttributeCollection>
      </AttributeGroup>
    </AttributePage>
  </Dataset>
</MartConfiguration>
